name: notebook
channels:
  - conda-forge
dependencies:
  - bokeh
  - contextily
  - dask
  - dask-labextension
  - datashader
  - distributed
  - fiona
  - gcsfs
  - geopandas
  - geoviews
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - ipykernel
  - ipyleaflet
  - ipywidgets
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab=3
  - matplotlib
  - mercantile
  - nbgitpuller
  - nomkl
  - pandas
  - pip
  - planet
  - python=3.12
  - python-graphviz
  - rasterio
  - requests
  - rioxarray
  - s3fs
  - shapely
  - xarray
  - zarr
  - sliderule
  #- pip:
   # - porder
   # - pygeotools
   # - git+https://github.com/dshean/imview.git
   # - git+https://github.com/dshean/demcoreg.git
