name: notebook
channels:
  - conda-forge
dependencies:
  - bokeh
  - contextily
  - dask
  - dask-labextension
  - datashader
  - distributed
  - fiona
  - gcsfs
  - geopandas
  - geoviews
  - h5netcdf
  - h5py
  - holoviews
  - hvplot
  - intake
  - intake-xarray
  - ipykernel
  - ipyleaflet
  - ipywidgets
#  - ipympl
  - jupyterhub-singleuser
  - jupyter-server-proxy
  - jupyterlab=2
  - matplotlib
  - mercantile
  - nb_conda_kernels
  - nbgitpuller
  - nodejs
  - nomkl
  - pandas
  - pip
  - planet
  - python=3.8
  - python-graphviz
  - rasterio
  - requests
  - rio-cogeo
  - rioxarray
  - s3fs
  - sat-search
  - shapely
  - xarray
  - zarr
  - pip:
    - porder
    - pygeotools
    - git+https://github.com/dshean/imview.git
    - git+https://github.com/dshean/demcoreg.git
    - git+https://github.com/friedrichknuth/driveanon.git
