name: asp
channels:
  - conda-forge
dependencies:
# from pangeo-stacks base-image
  - jupyterlab=1.2
  - jupyterhub=1.0
  - jupyter-server-proxy=1.1
  - nbgitpuller=0.7
  - dask=2.8
  - distributed=2.8
  - dask-kubernetes=0.10
  - dask-labextension=1.0
  - dask-gateway=0.5
  - tornado=6.0
  - bokeh=1.4
  - python-graphviz=0.13
  - pip=19.3
# Raster
  - xarray
  - h5py
  - h5netcdf
  - rasterio
  - rio-cogeo
  - mercantile
  - rioxarray
# Vector
  - pandas
  - geopandas
  - fiona
  - shapely
# Viz
  - holoviews
  - geoviews
  - hvplot
  - datashader
  - matplotlib
  - contextily
  - ipyleaflet
# IO
  - s3fs
  - gcsfs
  - intake
  - intake-xarray
  - zarr
  - sat-search
# Misc
  - nomkl
  - ipykernel
  - nb_conda_kernels
  - boto3
  - awscli
  - requests
  - planet
  - pip:
    - porder
    - pygeotools
    - git+https://github.com/dshean/imview.git
    - git+https://github.com/dshean/demcoreg.git
    - git+https://github.com/friedrichknuth/driveanon.git
