#!/bin/bash

# Install Ames stereo pipeline binary (~200Mb)
#e.g. https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/3.0.0/StereoPipeline-3.0.0-2021-07-27-x86_64-Linux.tar.bz2
DATE='2021-07-27'
VERSION="3.0.0"
NAME=StereoPipeline-$VERSION-$DATE-x86_64-Linux
wget -q https://github.com/NeoGeographyToolkit/StereoPipeline/releases/download/3.0.0/$NAME.tar.bz2
tar -xjf $NAME.tar.bz2
mv $NAME /srv/StereoPipeline
rm $NAME.tar.bz2

# EOF

